backend:
  name: git-gateway
  branch: main

# Publish mode for editorial workflow
publish_mode: editorial_workflow

# Media folder where uploads will be stored
media_folder: "public/uploads"
public_folder: "/uploads"

# Collections define the structure for content types
collections:
  - name: "frameworks"
    label: "Frameworks"
    folder: "content/frameworks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Website URL", name: "websiteUrl", widget: "string" }
      - { label: "Repository URL", name: "repositoryUrl", widget: "string" }
      - { label: "Category", name: "category", widget: "relation", collection: "categories", search_fields: ["name"], value_field: "slug", display_fields: ["name"] }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Created At", name: "createdAt", widget: "datetime" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime" }

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Slug", name: "slug", widget: "string" }
  
  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Author Name", name: "authorName", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Related Frameworks", name: "relatedFrameworks", widget: "relation", collection: "frameworks", search_fields: ["name"], value_field: "slug", display_fields: ["name"], multiple: true, required: false }
